"""Initial migration

Revision ID: 75a7c943063f
Revises: 
Create Date: 2026-03-03 09:13:49.697498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '75a7c943063f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model',
                    sa.Column('supplier', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('base_model', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('default_model', sa.Boolean(), nullable=False),
                    sa.Column('llm_type', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=False),
                    sa.Column('backup_model', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('api_domain', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('protocol', sa.Integer(), nullable=False),
                    sa.Column('config', sa.Text(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('hashed_password',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('oid', sa.BigInteger(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspace_users',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uid', sa.BigInteger(), nullable=False),
                    sa.Column('oid', sa.BigInteger(), nullable=False),
                    sa.Column('role', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('workspaces',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_workspaces_name'),
                    'workspaces', ['name'], unique=True)
    op.create_table('sessionmodel',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionmodel')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('workspace_users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ai_model')
    # ### end Alembic commands ###
